name: Docker Image CD

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: package jar file
      run: mvn docker:start package -DDB_PASSWORD=root -DJWT_SECRET=secret docker:stop
      
    - name: display files
      run: ls
      
    #- name: Build the Docker image
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
