name: Docker Image CD

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: package jar file
      run: mvn docker:start package -DDB_PASSWORD=root -DJWT_SECRET=secret docker:stop
      
      
    - name: Build the Docker image
      run: docker build -t amtsilkyroad/auth .
      
    - name: Login to dockerhub
      run: docker login -u amtsilkyroad -p uvAwKKdtARa6ST3
      
    - name: Push image to dockerhub
      run: docker push amtsilkyroad/auth
